### PR TITLE
Mods required by Weiquns amrex Geometry changes (5/21)

### PR DESCRIPTION
**Pull request by drummerdoc**
Includes Geometry stuff and a few RunOn::Cpu args to get the code to compile with current version of AMReX.

### CODE REVIEW

**Comment by jrood-nrel** [comment]
What's happening here? Didn't we just do this in https://github.com/AMReX-Combustion/PeleC/pull/87? And why isn't GitHub showing more conflicts than just `Source/PeleC_MOL.cpp` in this PR (unless the changes are exact in the other files I guess)? In my local updated `development` branch, I have all these changes.

**Comment by drummerdoc** [comment]
I dunno.  You guys are so fancy that us simple folks out west here can't seem to make sense of things.  I git-pulled in PeleC's `master` branch with the recursive BS to get all the submodules in place, and tried to build in one of the tutorials areas and got the errors I had to fix.  But, then I also checked out `development` and tried the same.  Both failed the same way, so I made a new branch and this PR.  Not sure what the magic incantation is, but old-school it's broken

**Comment by rgrout** [comment]
Maybe bad timing - I merged #87 earlier today, any chance overlapped?

When I look at development branch in github I definitely see the changes in this pull request.

**Comment by drummerdoc** [comment]
Weird, because I did a pull right before generating the PR.  Whatever.  I'll delete this PR.

**Comment by jrood-nrel** [comment]
The `GNUMakefile`s in the Exec directory are all over the place either using `PELEC_HOME` or `PELE_HOME` or `../../Make.PeleC` to find `Make.PeleC`. The submodules shouldn't matter if you have your own `AMREX_HOME` and `PELE_PHYSICS_HOME` set. I will make a PR to sort out all the `GNUMakefile`s. I am not able to reproduce any errors in the `Tutorials` on the `development` branch except for some them not finding `Make.PeleC`.

**Comment by drummerdoc** [comment]
Maybe there was a glitch in GH.  But yeah, coming from an environment where I depended on the use of PELE_HOME, PELEC_HOME, PELELM_HOME, PELE_PHYSICS_HOME, IAMR_HOME and AMREX_HOME, the makefiles need to probably be sure to avoid the ?= syntax so things don't get confused.  the ones I looked at seemed good with that, but it wasn't clear to me the difference in your usage between PELE_HOME and PELEC_HOME.

**Comment by drummerdoc** [comment]
Also, when I went back to my PeleC `development` branch and did another "git pull", it picked up the #87 changes (it did not have the `marc/fix_geoms` stuff merged in.  So, indeed I think there was a glitch in the GH pages.

**Comment by jrood-nrel** [comment]
The old school tests passed with the latest `development` https://amrex-combustion.github.io/PeleCRegressionTestResults . Also, the behavior of the `<REPO>_HOME` variables should work exactly like before. If they aren't working, we need to fix the `GNUMakefile`s. The submodules provide a fallback so if you have none set, it will default to them, or you can set the `HOME` variables to the submodules as well. However, my intent with the submodules is so that we can use them to help reduce the possibility of people being on different commits in all the repos in the future.

**Pull request closed without merging**
