### PR TITLE
adding cavity flame input files

### PR DESCRIPTION
**Pull request by hsitaram**
1) added case files from PeleC paper:  Sitaraman et al. "Adaptive mesh based combustion simulations of direct fuel injection effects in a supersonic cavity flame-holder." Combustion and Flame 232 (2021): 111531.

2) removed extrusion step in extruded triangles. The triangle planes are already extruded.

### CODE REVIEW

**Review by marchdf — COMMENTED** [review]
Can you remove the PelePhysics submod update? Otherwise looks good

**Comment by hsitaram** [comment]
fixed the pelephysics update. although it says "changed 0 files", not sure what that means.. I never get submodules right

**Review by marchdf — APPROVED** [review]

**Comment by baperry2** [comment]
Looking into some issues with the initialization, which appears to cause issues with excessive expansion near the leading edge of the cavity particularly on coarser grids

**Review by baperry2 — APPROVED** [review]
I added some different initialization options that appear to make the initial transient more stable. With these options, everything is stable even on a 128x32x8 grid with no refinement.

**Comment by jrood-nrel** [comment]
I tried removing the submodule update on this branch, and I think this branch's history has a problem. I think we should play it careful with the submodule history so I made another PR for this https://github.com/AMReX-Combustion/PeleC/pull/649 .

**Pull request closed without merging**
