### PR TITLE
Changes in PeleC to build against AMReX development branch. 

### PR DESCRIPTION
**Pull request by sireeveslbl**
Changes in PeleC to use the DefaultGeometry() object instead of the now deprocated static variables/functions in the Geometry class. Also changed FineAdd and CrseAdd in flux registers to have the 5th argument RunOn::Cpu.

These changes are in: 
PeleC.cpp 
PeleC_advance.cpp
PeleC_hydro.cpp 
PeleC_setup.cpp 
PeleC_MOL.cpp 
PeleC_io.cpp

### CODE REVIEW

**Comment by rgrout** [comment]
Thanks for this - it’s git Merge day 2 days ago and I want to do that before merging this pull request. Will do this evening....

**Comment by jrood-nrel** [comment]
@sireeveslbl You will want to update the AMReX submodule in this PR as well to get the CI to pass.

**Comment by sireeveslbl** [comment]
@jrood-nrel I'm afraid I don't really know how to do that. 
I did the git submodule update, and it still seems to be failing, and it appears that Travis is still failing. It looked like Travis was using the branch of AMReX that I was, the latest development commit. I am not familiar with git submodules.

**Comment by jrood-nrel** [comment]
@sireeveslbl I hope you don't mind I pushed some changes to this branch to try to solve the CI. There were some missing changes to PeleC to get the MOL exe and EB exes to build with the AMReX changes as well.

**Comment by jrood-nrel** [comment]
I should note for future PRs since the CI here uses CMake/CTest, when AMReX changes files around, they update their `CMakeLists.txt` so I just copy and pasted their list into `CMake/amrex_sources.cmake` in this repo to pull in the changes.

**Comment by sireeveslbl** [comment]
Thanks @jrood-nrel I don't mind that you fixed the CI!

**Pull request merged**
