### PR TITLE
Simplify diffusion flux calls by removing need for sparse EB struct

### PR DESCRIPTION
**Pull request by marchdf**
I think this is going to be one of many passes to start removing the sparse EB stuct stuff. 

As it stands:
- TG shows zero diffs with this:
```
fcompare.llvm.ex plt00010 orig/plt00010

            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                          0                         0
 Temp                                             0                         0
 rho_AIR                                          0                         0
 pressure                                         0                         0
 magvort                                          0                         0
 x_velocity                                       0                         0
 y_velocity                                       0                         0
 z_velocity                                       0                         0
 magvel                                           0                         0
 PLOTFILE AGREE
```

- EB-C10 shows zero diffs after 1 time step. But it starts to show diffs after 10:
```
fcompare.llvm.ex plt00010 orig/plt00010

            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                            1.437034085e-13           1.221930097e-10
 xmom                               1.317701503e-11           6.074641266e-12
 ymom                                1.81393777e-10           9.289685792e-08
 zmom                               2.407705198e-10           1.234358553e-07
 rho_E                              5.681533366e-05           2.242645273e-11
 rho_e                              5.692942068e-05            2.24889264e-11
 Temp                               3.043726338e-08           1.014276429e-10
 rho_AIR                            1.437034085e-13           1.221930097e-10
 pressure                           2.277176827e-05            2.24889264e-11
 kineng                             1.138477046e-07           5.687605118e-11
 enstrophy                          9.230308251e-07           5.912866196e-10
 soundspeed                         1.761007297e-06           5.071420924e-11
 MachNumber                         2.647701502e-12           4.926423943e-11
 entropy                                          0                         0
 magvort                            9.377209835e-07            5.52749737e-10
 divu                               9.678583148e-07           3.413065229e-08
 eint_E                                0.2183890343           1.014275324e-10
 eint_e                                0.2183890343           1.014275324e-10
 logden                             5.398215208e-11           1.820239227e-11
 x_velocity                         1.567175332e-07           8.398970725e-11
 y_velocity                         1.568169946e-07           8.746746098e-08
 z_velocity                         2.081355642e-07           1.162141533e-07
 magvel                              1.56472197e-07           8.385821744e-11
 radvel                             7.023731996e-08           3.766137871e-11
 magmom                             1.319944154e-11           6.084979725e-12
 cp                                               0                         0
 cv                                               0                         0
 x                                                0                         0
 y                                                0                         0
 z                                                0                         0
 viscosity                                        0                         0
 bulk_viscosity                                   0                         0
 conductivity                                     0                         0
 D(AIR)                                           0                         0
 vfrac                                            0                         0
```
I am very confused as to why it doesn't diff after 1 step but it does on subsequent steps.

I am also a little worried about `pc_move_transcoefs_to_ec`. It's never been EB aware... should it be?!

### CODE REVIEW

**Comment by marchdf** [comment]
I am actually going to say I am ok with this. EB-C10 is a quiescent flow initially. EB-C1 which is an MMS case is much more interesting (non-zero fluxes). 100 steps with dev branch and this branch gives me machine diffs:
```            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                             4.33680869e-19           3.367086133e-16
 Temp                               1.705302566e-13           5.143186602e-16
 rho_AIR                             4.33680869e-19           3.367086133e-16
 pressure                           8.149072528e-10            7.71988953e-16
 magvort                            1.455191523e-11            4.04060863e-16
 x_velocity                         1.818989404e-12           4.993697749e-16
 y_velocity                         1.818989404e-12           4.993697749e-16
 z_velocity                         1.818989404e-12           4.993697749e-16
 magvel                             1.818989404e-12           2.912749696e-16
 rhommserror                         4.33680869e-19             1.9535114e-15
 ummserror                          1.818989404e-12           3.516479422e-16
 vmmserror                          1.818989404e-12           3.516479422e-16
 wmmserror                          1.818989404e-12           3.516479422e-16
 pmmserror                           6.98491931e-10           1.639866137e-14
 vfrac                                            0                         0
```
So I am now ok with this code. Though I should probably check a multi-species case.

**Comment by marchdf** [comment]
EB C8 with diffusion turned on, 10 steps, max_level = 1, 1 MPI rank -> looks good too, machine diffs: [comp.txt](https://github.com/AMReX-Combustion/PeleC/files/11727489/comp.txt)

**Review by jrood-nrel — APPROVED** [review]

**Review by baperry2 — APPROVED** [review]
Looks good to me.

I don't believe `pc_move_transcoefs_to_ec` needs to be EB aware, as that's the location where the fluxes get computed regardless of EB. It also gets used for LES, but LES isn't operable with EB anyway.

**Comment by marchdf** [comment]
I should have documented the speedup difference. I used the challenge problem with these additional CLI options: `max_step=100 amr.max_level=0 pelec.do_react=0 amr.checkpoint_files_output=0 amr.plot_files_output=0 amr.n_cell=128 128 32`. 

New code 37a33715 [full profile](https://github.com/AMReX-Combustion/PeleC/files/11761688/new.txt):

```-----------------------------------------------------------------------------------------------
Name                                            NCalls  Excl. Min  Excl. Avg  Excl. Max   Max %
-----------------------------------------------------------------------------------------------
PeleC::getMOLSrcTerm()                             200      24.85      24.85      24.85  42.17%
PeleC::extend_signed_distance()                     51      14.76      14.76      14.76  25.04%
PeleC::initialize_eb2_structs()                     51      11.74      11.74      11.74  19.92%
amrex::Copy()                                     5250      1.589      1.589      1.589   2.70%
PeleC::initialize_signed_distance()                 51      1.149      1.149      1.149   1.95%
PeleC::pc_apply_face_stencil()                     800      1.003      1.003      1.003   1.70%
StateData::FillBoundary(geom)                      804     0.9755     0.9755     0.9755   1.66%
Amr::readProbinFile()                                1     0.6451     0.6451     0.6451   1.09%
```

Old code 2ee36d71 [full profile](https://github.com/AMReX-Combustion/PeleC/files/11761700/old.txt)

```
-----------------------------------------------------------------------------------------------
Name                                            NCalls  Excl. Min  Excl. Avg  Excl. Max   Max %
-----------------------------------------------------------------------------------------------
PeleC::getMOLSrcTerm()                             200      26.68      26.68      26.68  44.11%
PeleC::extend_signed_distance()                     51      14.76      14.76      14.76  24.40%
PeleC::initialize_eb2_structs()                     51      11.77      11.77      11.77  19.45%
amrex::Copy()                                     5250      1.595      1.595      1.595   2.64%
PeleC::initialize_signed_distance()                 51      1.151      1.151      1.151   1.90%
PeleC::pc_apply_face_stencil()                     800      1.006      1.006      1.006   1.66%
StateData::FillBoundary(geom)                      804     0.8523     0.8523     0.8523   1.41%
Amr::readProbinFile()                                1     0.3918     0.3918     0.3918   0.65%
```

Almost a 7% speedup in `getMOLSrcTerm`!

**Pull request merged**
