### PR TITLE
Fix the Riemann solver for species

### PR DESCRIPTION
**Pull request by marchdf**
Opening this up for discussion as well. 

The gist here is the following: instead of using `rho` and `Y` interpolating those directly, we interpolate in the `rho Y` space and compute `rho` from there (every time we need it). This means that we now follow the same philosophy as that done in computing the MOL slopes. 

For a 1D regular *multi-species* shock tube, this PR fixes violation of mass fraction bounds (when running with MOL):

Baseline code:
```
TIME = 1.959e-06 density     MIN = 0.00011999864    MAX = 0.00096000048
TIME = 1.959e-06 x_velocity  MIN = -1.3365077       MAX = 95397.347
TIME = 1.959e-06 y_velocity  MIN = 0                MAX = 0
TIME = 1.959e-06 z_velocity  MIN = 0                MAX = 0
TIME = 1.959e-06 eint_e      MIN = -2.9835117e+09   MAX = 2.9448659e+10
TIME = 1.959e-06 Temp        MIN = 401.16541        MAX = 3509.623
TIME = 1.959e-06 pressure    MIN = 999981.1         MAX = 10000006
TIME = 1.959e-06 massfrac    MIN = -1.577142e-05    MAX = 1.0000158
TIME = 1.959e-06 sumYminus1  MIN = -2.9976022e-15   MAX = 2.6645353e-15
TIME = 1.959e-06 H2          MIN = 0                MAX = 0
TIME = 1.959e-06 H           MIN = 0                MAX = 0
TIME = 1.959e-06 AR          MIN = 0                MAX = 0
TIME = 1.959e-06 N2          MIN = -1.577142e-05    MAX = 1
TIME = 1.959e-06 HE          MIN = 0                MAX = 1.0000158
TIME = 1.959e-06 O           MIN = 0                MAX = 0
TIME = 1.959e-06 OH          MIN = 0                MAX = 0
TIME = 1.959e-06 HCO         MIN = 0                MAX = 0
TIME = 1.959e-06 HO2         MIN = 0                MAX = 0
TIME = 1.959e-06 H2O         MIN = 0                MAX = 0
TIME = 1.959e-06 CO          MIN = 0                MAX = 0
TIME = 1.959e-06 O2          MIN = 0                MAX = 0
TIME = 1.959e-06 H2O2        MIN = 0                MAX = 0
TIME = 1.959e-06 CO2         MIN = 0                MAX = 0
```

Code from this PR:
```
TIME = 1.959e-06 density     MIN = 0.00011999864    MAX = 0.00096000048
TIME = 1.959e-06 x_velocity  MIN = -1.336556        MAX = 95397.343
TIME = 1.959e-06 y_velocity  MIN = 0                MAX = 0
TIME = 1.959e-06 z_velocity  MIN = 0                MAX = 0
TIME = 1.959e-06 eint_e      MIN = -2.9835117e+09   MAX = 2.9448659e+10
TIME = 1.959e-06 Temp        MIN = 401.16541        MAX = 3509.623
TIME = 1.959e-06 pressure    MIN = 999981.1         MAX = 10000006
TIME = 1.959e-06 massfrac    MIN = 0                MAX = 1
TIME = 1.959e-06 sumYminus1  MIN = -2.7755576e-15   MAX = 3.3306691e-15
TIME = 1.959e-06 H2          MIN = 0                MAX = 0
TIME = 1.959e-06 H           MIN = 0                MAX = 0
TIME = 1.959e-06 AR          MIN = 0                MAX = 0
TIME = 1.959e-06 N2          MIN = 0                MAX = 1
TIME = 1.959e-06 HE          MIN = 0                MAX = 1
TIME = 1.959e-06 O           MIN = 0                MAX = 0
TIME = 1.959e-06 OH          MIN = 0                MAX = 0
TIME = 1.959e-06 HCO         MIN = 0                MAX = 0
TIME = 1.959e-06 HO2         MIN = 0                MAX = 0
TIME = 1.959e-06 H2O         MIN = 0                MAX = 0
TIME = 1.959e-06 CO          MIN = 0                MAX = 0
TIME = 1.959e-06 O2          MIN = 0                MAX = 0
TIME = 1.959e-06 H2O2        MIN = 0                MAX = 0
TIME = 1.959e-06 CO2         MIN = 0                MAX = 0
```

This doesn't affect the overall solution (blue: baseline, green: this PR):

**N2 mass fraction**
Screen Shot 2021-11-30 at 11 54 33 AM

**Density**
Screen Shot 2021-11-30 at 11 57 16 AM

**Velocity**
Screen Shot 2021-11-30 at 11 57 59 AM

**Takeaways**:
- this PR solves the out of bounds mass fractions in this multispecies shock tube.

Can I get help testing this on other non-EB configurations? Specifically the Jet in Crossflow.

### CODE REVIEW

**Comment by baperry2** [comment]
I've been testing these changes on the 2D sco2 combustor geometry. Previously it was failing after 600 steps, but with these changes, it has run ~10000 steps and is still going strong. Minimum massfraction around -1e-10, which seems ok to me. Below - minimum mass fraction or abs(min) in logspace: blue line is old code that failed, cyan line is with these modifications (and PR #380).
massfrac

massfrac-log

Screen Shot 2021-12-01 at 10 33 52 AM

**Comment by baperry2** [comment]
After running the sco2 combustor case further, it failed. However, if I clip concentrations before computing reaction rates (https://github.com/AMReX-Combustion/PelePhysics/pull/223/files), the small -1e-10 mass fractions bounce around at that level, but do not grow. (Same figure as above, but now blue is the case with both these fixes and clipping)

massfrac-log

**Comment by marchdf** [comment]
To do for Marc:
- [x] ensure this works with godunov (PPM/PLM) (update the rhoY flux call, ensure NPASSIVE does not include Y?) -> deal with this in another PR
- [x] check to see if LLF needs to be updated in the same way
- [x] verify the test cases (make sure they work, make sure they preserve the bounds, etc)

**Comment by marchdf** [comment]
This is @mjrahimi 3D Jet In Crossflow case. It used to generate negative mass fractions. With this PR, it doesn't. And it doesn't generate negative mass fractions for over 320k steps.

Screen Shot 2021-12-01 at 1 13 43 PM

**Review by hsitaram — APPROVED** [review]

**Comment by marchdf** [comment]
@olgadoronina has run yet another case that benefits from this PR (injection of fuel into sCO2 combustor)... I am marking this as ready to merge.

**Review by drummerdoc — APPROVED** [review]

**Review by jrood-nrel — APPROVED** [review]

**Review by baperry2 — APPROVED** [review]

**Pull request merged**
