### PR TITLE
Check if PELE_COMPILE_AJACOBIAN is set

### PR DESCRIPTION
**Pull request by gardner48**

### CODE REVIEW

**Comment by jrood-nrel** [comment]
I guess I'm probably fine with this. I'm not sure what to do about the jacobian in general yet. My intention was to just add the define in the `GNUmakefile` when necessary until we narrow in on something: https://github.com/AMReX-Combustion/PeleC/blob/d044eec3a6ad65b31b9088673701f37ff0e06a2c/Exec/RegTests/MMS/GNUmakefile#L37

**Comment by gardner48** [comment]
This seemed like the easiest solution for the moment but maybe it would be better to add this define based on other options like `PELE_USE_MAGMA` and `PELE_USE_KLU` (and possibly `PELE_USE_GINKGO` in the future)

**Review by jrood-nrel — APPROVED** [review]

**Comment by jrood-nrel** [comment]
@gardner48 If you click "update branch" this should automerge.

**Comment by gardner48** [comment]
@jrood-nrel looks like I need an approval for the CI workflow to run

**Comment by jrood-nrel** [comment]
Ok let's try this again. Can you click the update branch button?

**Pull request merged**
