### PR TITLE
abort on unused parmparse variables in input file in tests

### PR DESCRIPTION
**Pull request by baperry2**
So excess/deprecated inputs don't build up and cause confusion.

### CODE REVIEW

**Comment by baperry2** [comment]
@marchdf @jrood-nrel how do we feel about this? I haven't gone through all the input files yet, but the ones changed here are representative. It catches some deprecated and/or irrelevant inputs, but mostly just catches `amr.ref_ratio` and amr.regrid_int` for cases without AMR.

**Comment by jrood-nrel** [comment]
Love it.

**Comment by marchdf** [comment]
I like it. I wish we could ignore the ref_ratio and regrid_int when max_level = 0. It's less stuff to change when we change the max level... but maybe that's too much to ask?

**Comment by baperry2** [comment]
We could put dummy queries for these just so they always get touched, but I'm not a big fan of that. IMO not a big deal just to uncomment those lines when adding levels.

**Review by jrood-nrel — APPROVED** [review]

**Review by marchdf — APPROVED** [review]

**Comment by marchdf** [comment]
yeah probably fine.

**Comment by baperry2** [comment]
@marchdf based on what this uncovered, it looks like the forcing for HIT case wasn't actually active, which I think I fixed. Also, the "moving plane" EB geometry and corresponding EB-Plane test seem to not really do anything, so I deleted them. Can you double check these changes?

**Review by jrood-nrel — APPROVED** [review]

**Review by marchdf — APPROVED** [review]

**Comment by marchdf** [comment]
nice work!

**Pull request merged**
