### PR TITLE
Add capability to explicitly untag EB surfaces

### PR DESCRIPTION
**Pull request by marchdf**
Totally stolen from LM

### CODE REVIEW

**Comment by marchdf** [comment]
EB C8 baseline:
Screen Shot 2022-02-28 at 3 39 13 PM

With this PR and `taggging..max_eb_refine_lev=0`: 
Screen Shot 2022-02-28 at 3 36 59 PM

**Review by drummerdoc — APPROVED** [review]
Can't really check in detail, but looks good (and is needed).

**Review by esclapez — APPROVED** [review]
Successfully tested on Perlmutter, so the machinery is working.

**Comment by jrood-nrel** [comment]
Yahtzee

**Pull request merged**
