### PR TITLE
Remove elixir

### PR DESCRIPTION
**Pull request by marchdf**

### CODE REVIEW

**Comment by marchdf** [comment]
`development` branch on Eagle V100 GPU with Cuda 11.2.2:
```
Test project /home/mhenryde/combustion/Pele/PeleC/Build
      Start  1: multispecsod-1
 1/27 Test  #1: multispecsod-1 ...................   Passed    7.72 sec
      Start  2: pmf-1
 2/27 Test  #2: pmf-1 ............................   Passed    8.34 sec
      Start  3: pmf-srk-1
 3/27 Test  #3: pmf-srk-1 ........................   Passed    8.11 sec
      Start  4: tg-1
 4/27 Test  #4: tg-1 .............................   Passed   12.71 sec
      Start  5: tg-2
 5/27 Test  #5: tg-2 .............................   Passed   10.15 sec
      Start  6: hit-1
 6/27 Test  #6: hit-1 ............................   Passed    8.89 sec
      Start  7: hit-2
 7/27 Test  #7: hit-2 ............................   Passed    7.59 sec
      Start  8: hit-3
 8/27 Test  #8: hit-3 ............................   Passed    7.67 sec
      Start  9: sod-1
 9/27 Test  #9: sod-1 ............................   Passed    7.97 sec
      Start 10: sod-2
10/27 Test #10: sod-2 ............................   Passed    8.72 sec
      Start 11: eb-c4
11/27 Test #11: eb-c4 ............................   Passed   11.77 sec
      Start 12: eb-c5
12/27 Test #12: eb-c5 ............................   Passed   12.56 sec
      Start 13: eb-c9
13/27 Test #13: eb-c9 ............................   Passed    8.18 sec
      Start 14: eb-c10
14/27 Test #14: eb-c10 ...........................   Passed    7.93 sec
      Start 15: eb-c11
15/27 Test #15: eb-c11 ...........................   Passed    7.73 sec
      Start 16: eb-c12
16/27 Test #16: eb-c12 ...........................   Passed    7.80 sec
      Start 17: tg-3
17/27 Test #17: tg-3 .............................   Passed    9.51 sec
      Start 18: tg-4
18/27 Test #18: tg-4 .............................   Passed   10.01 sec
      Start 19: sedov-1
19/27 Test #19: sedov-1 ..........................   Passed    9.53 sec
      Start 20: shu-osher-1
20/27 Test #20: shu-osher-1 ......................   Passed    7.64 sec
      Start 21: zerod-1
21/27 Test #21: zerod-1 ..........................   Passed    7.62 sec
      Start 22: eb-c3
22/27 Test #22: eb-c3 ............................***Failed   12.70 sec
      Start 23: eb-c7
23/27 Test #23: eb-c7 ............................   Passed   17.75 sec
      Start 24: eb-c8
24/27 Test #24: eb-c8 ............................   Passed   24.12 sec
      Start 25: eb-bluffbody-1
25/27 Test #25: eb-bluffbody-1 ...................   Passed   15.38 sec
      Start 26: eb-plane-1
26/27 Test #26: eb-plane-1 .......................   Passed   18.68 sec
      Start 27: unit-tests
27/27 Test #27: unit-tests .......................   Passed    4.59 sec

96% tests passed, 1 tests failed out of 27

Label Time Summary:
no-ci         = 265.89 sec*proc (10 tests)
regression    = 553.58 sec*proc (26 tests)
unit          =   4.59 sec*proc (1 test)

Total Test time (real) = 281.57 sec

The following tests FAILED:
         22 - eb-c3 (Failed)
Errors while running CTest
```

**Comment by marchdf** [comment]
This branch with cuda 10.2:
```
Test project /home/mhenryde/combustion/Pele/PeleC/Build
      Start  1: multispecsod-1
 1/27 Test  #1: multispecsod-1 ...................   Passed   10.30 sec
      Start  2: pmf-1
 2/27 Test  #2: pmf-1 ............................   Passed   12.25 sec
      Start  3: pmf-srk-1
 3/27 Test  #3: pmf-srk-1 ........................   Passed   12.46 sec
      Start  4: tg-1
 4/27 Test  #4: tg-1 .............................   Passed   10.44 sec
      Start  5: tg-2
 5/27 Test  #5: tg-2 .............................   Passed   10.66 sec
      Start  6: hit-1
 6/27 Test  #6: hit-1 ............................   Passed   10.44 sec
      Start  7: hit-2
 7/27 Test  #7: hit-2 ............................   Passed   11.31 sec
      Start  8: hit-3
 8/27 Test  #8: hit-3 ............................   Passed   10.15 sec
      Start  9: sod-1
 9/27 Test  #9: sod-1 ............................   Passed   12.18 sec
      Start 10: sod-2
10/27 Test #10: sod-2 ............................   Passed   10.43 sec
      Start 11: eb-c4
11/27 Test #11: eb-c4 ............................   Passed   13.81 sec
      Start 12: eb-c5
12/27 Test #12: eb-c5 ............................   Passed   12.86 sec
      Start 13: eb-c9
13/27 Test #13: eb-c9 ............................   Passed   11.00 sec
      Start 14: eb-c10
14/27 Test #14: eb-c10 ...........................***Failed   12.38 sec
      Start 15: eb-c11
15/27 Test #15: eb-c11 ...........................   Passed   10.16 sec
      Start 16: eb-c12
16/27 Test #16: eb-c12 ...........................   Passed   10.27 sec
      Start 17: tg-3
17/27 Test #17: tg-3 .............................   Passed   11.48 sec
      Start 18: tg-4
18/27 Test #18: tg-4 .............................   Passed   13.58 sec
      Start 19: sedov-1
19/27 Test #19: sedov-1 ..........................   Passed   11.98 sec
      Start 20: shu-osher-1
20/27 Test #20: shu-osher-1 ......................   Passed   10.08 sec
      Start 21: zerod-1
21/27 Test #21: zerod-1 ..........................   Passed   11.09 sec
      Start 22: eb-c3
22/27 Test #22: eb-c3 ............................***Failed   15.05 sec
      Start 23: eb-c7
23/27 Test #23: eb-c7 ............................   Passed   21.31 sec
      Start 24: eb-c8
24/27 Test #24: eb-c8 ............................   Passed   28.80 sec
      Start 25: eb-bluffbody-1
25/27 Test #25: eb-bluffbody-1 ...................   Passed   19.46 sec
      Start 26: eb-plane-1
26/27 Test #26: eb-plane-1 .......................   Passed   22.81 sec
      Start 27: unit-tests
27/27 Test #27: unit-tests .......................   Passed    4.96 sec

93% tests passed, 2 tests failed out of 27

Label Time Summary:
no-ci         = 331.28 sec*proc (10 tests)
regression    = 693.46 sec*proc (26 tests)
unit          =   4.96 sec*proc (1 test)

Total Test time (real) = 351.89 sec

The following tests FAILED:
         14 - eb-c10 (Failed)
         22 - eb-c3 (Failed)
Errors while running CTest
```

Diffs on C10 are:
```
14/27 Testing: eb-c10
14/27 Test: eb-c10
Command: "/usr/bin/sh" "-c" "/opt/hpe/hpc/mpt/mpt-2.22/bin/mpiexec -n 2  /home/mhenryde/combustion/Pele/PeleC/Build/Exec/RegTests/EB-C10/PeleC-EB-C10  /home/mhenryde/combustion/Pele/PeleC/Build/Exec/RegTests/EB-C10/tests/eb-c10/eb-c10.i max_step=10 amr.plot_file=plt amr.checkpoint_files_output=0 amr.plot_files_output=1 amrex.signal_handling=1 amrex.fpe_trap_invalid=1 amrex.fpe_trap_zero=1 amrex.fpe_trap_overflow=1 > eb-c10.log && /opt/hpe/hpc/mpt/mpt-2.22/bin/mpiexec -n \
2  /home/mhenryde/combustion/Pele/PeleC/Build/Submodules/AMReX/Tools/Plotfile/fcompare -r 1e-12 --abs_tol 1.0e-12 /home/mhenryde/combustion/Pele/PeleC/Tests/PeleCGoldFiles/Linux/GNU/8.4.0/EB-C10/tests/eb-c10/plt00010 /home/mhenryde/combustion/Pele/PeleC/Build/Exec/RegTests/EB-C10/tests/eb-c10/plt00010"
Directory: /home/mhenryde/combustion/Pele/PeleC/Build/Exec/RegTests/EB-C10/tests/eb-c10/
"eb-c10" start time: Jul 19 15:29 MDT
Output:
----------------------------------------------------------

            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                            1.084202172e-18           9.219132084e-16
 xmom                               9.325873407e-15           4.299282971e-15
 ymom                               1.012709881e-14           5.333430413e-12
 zmom                               9.069134332e-15           4.776254065e-12
 rho_E                              1.862645149e-09           7.352343998e-16
 rho_e                              1.862645149e-09           7.358052891e-16
 Temp                               2.842170943e-13           9.471360059e-16
 rho_O2                             1.301042607e-18            1.10629585e-15
 rho_N2                                           0                         0
 pressure                           9.313225746e-10           9.197566114e-16
 kineng                             1.705302566e-11           8.519414542e-15
 enstrophy                          3.490185918e-11           3.668274881e-14
 soundspeed                         2.182787284e-11           6.286162858e-16
 MachNumber                         2.428612866e-16            4.51875475e-15
 entropy                                          0                         0
 magvort                            2.691535883e-11           2.032196594e-14
 divu                               9.622524999e-11           1.781751621e-14
 eint_E                             2.384185791e-06           1.107328681e-15
 eint_e                             2.384185791e-06           1.107328681e-15
 logden                             8.881784197e-16           2.994892548e-16
 x_velocity                         8.185452316e-12           4.386810277e-15
 y_velocity                          9.29856192e-12            5.33348404e-12
 z_velocity                         7.979172878e-12           4.576706759e-12
 magvel                             8.185452316e-12           4.386809948e-15
 radvel                             7.958078641e-12           4.267112001e-15
 magmom                             9.769962617e-15           4.504010578e-15
 vfrac                                            0                         0
 cp                                               0                         0
 cv                                               0                         0
srun: error: r104u33: tasks 0-1: Exited with exit code 1
srun: Terminating job step 7153032.28
<end of output>
Test time =  12.38 sec
----------------------------------------------------------
Test Failed.
"eb-c10" end time: Jul 19 15:29 MDT
"eb-c10" time elapsed: 00:00:12
----------------------------------------------------------
```

**Comment by marchdf** [comment]
On cuda 11.2.2 and V100 GPU, `srun -N 1 ./pelec tests/tg-1/tg-1.i max_step=250 amr.max_grid_size=8`:

`development` branch:
```
STEP = 249 TIME = 0.0001799510494 DT = 7.424341252e-07
...estimated hydro-limited timestep at level 0: 7.424403424e-07
PeleC::estTimeStep (hydro-limited) at level 0:  estdt = 7.424403424e-07
[Level 0 step 250] ADVANCE with dt = 7.424403424e-07
... Computing diffusion terms at t^(n)
... Computing hydro advance
... Computing diffusion terms at t^(n+1,1)
[Level 0 step 250] Advanced 262144 cells
TIME= 0.0001806934897 MASS        = 0.009412229059
TIME= 0.0001806934897 XMOM        = -9.020562075e-17
TIME= 0.0001806934897 YMOM        = 8.456776945e-17
TIME= 0.0001806934897 ZMOM        = 1.076938018e-15
TIME= 0.0001806934897 RHO*e       = 20260252.82
TIME= 0.0001806934897 RHO*K       = 13929.1825
TIME= 0.0001806934897 RHO*E       = 20274182
TIME= 0.0001806934897 ENSTROPHY   = 598743.9151
TIME= 0.0001806934897 FUEL PROD   = 0
TIME= 0.0001806934897 TEMP        = 2400.030104
[STEP 250] Coarse TimeStep time: 0.391814537
[STEP 250] FAB kilobyte spread across MPI nodes: [775152 ... 775152]
STEP = 250 TIME = 0.0001806934897 DT = 7.424403424e-07
CHECKPOINT: file = chk00250
checkPoint() time = 0.137802646 secs.
PLOTFILE: file = plt00250
Write plotfile time = 0.174721684  seconds
Ending run at 22:05:50 UTC on 2021-07-19.
Run time = 110.5617393
Run time w/o init = 110.1693385
```

this branch:
```
STEP = 249 TIME = 0.0001799510494 DT = 7.424341252e-07
...estimated hydro-limited timestep at level 0: 7.424403424e-07
PeleC::estTimeStep (hydro-limited) at level 0:  estdt = 7.424403424e-07
[Level 0 step 250] ADVANCE with dt = 7.424403424e-07
... Computing diffusion terms at t^(n)
... Computing hydro advance
... Computing diffusion terms at t^(n+1,1)
[Level 0 step 250] Advanced 262144 cells
TIME= 0.0001806934897 MASS        = 0.009412229059
TIME= 0.0001806934897 XMOM        = -9.020562075e-17
TIME= 0.0001806934897 YMOM        = 8.456776945e-17
TIME= 0.0001806934897 ZMOM        = 1.076938018e-15
TIME= 0.0001806934897 RHO*e       = 20260252.82
TIME= 0.0001806934897 RHO*K       = 13929.1825
TIME= 0.0001806934897 RHO*E       = 20274182
TIME= 0.0001806934897 ENSTROPHY   = 598743.9151
TIME= 0.0001806934897 FUEL PROD   = 0
TIME= 0.0001806934897 TEMP        = 2400.030104
[STEP 250] Coarse TimeStep time: 0.280530929
[STEP 250] FAB kilobyte spread across MPI nodes: [775152 ... 775152]
STEP = 250 TIME = 0.0001806934897 DT = 7.424403424e-07
CHECKPOINT: file = chk00250
checkPoint() time = 0.135809995 secs.
PLOTFILE: file = plt00250
Write plotfile time = 0.173807353  seconds
Ending run at 22:03:22 UTC on 2021-07-19.
Run time = 70.76245097
Run time w/o init = 70.30897648
```

**Comment by drummerdoc** [comment]
I may be wrong, but that seems excellent.

**Review by jrood-nrel — APPROVED** [review]

**Pull request merged**
