### PR TITLE
Fixed bugs for using reactions with cuda turned on, removed outdated …

### PR DESCRIPTION
**Pull request by ldowen**
…USE_CUDA_SUNDIALS_PP

### CODE REVIEW

**Review by jrood-nrel — APPROVED** [review]
This looks good. I just don't fully understand the `Make.PeleC` changes. Are they for PelePhysics?

**Comment by hsitaram** [comment]
some of your changes I know where they are coming from - latest pelephysics. Unfortunately we have not upgraded our submodules (I know M day is going to yell at me!) to latest pelephysics.  Can we wait a bit before we merge this?

**Comment by ldowen** [comment]
@jrood-nrel Yeah the `USE_CUDA_SUNDIALS_PP` is deprecated in PelePhysics.
@hsitaram I suppose we can wait if these changes will cause issues for you.

**Comment by ldowen** [comment]
What sort of timeline would we expect for these changes?

**Comment by jrood-nrel** [comment]
I think these changes are fine with the current PelePhysics we're using. Except for the `Make.PeleC` changes. I don't understand the CVODE stuff, but I think that's fine too.

**Comment by jrood-nrel** [comment]
Actually we might just need to keep `USE_CUDA_SUNDIALS_PP = TRUE` around for our PelePhysics to work.

**Comment by jrood-nrel** [comment]
It looks like the latest PelePhysics fixes the SUNDIALS output using `printf` on every MPI rank so I'm going to start working on using the latest PelePhysics.

**Comment by drummerdoc** [comment]
> It looks like the latest PelePhysics fixes the SUNDIALS output using `printf` on every MPI rank so I'm going to start working on using the latest PelePhysics.

Yeah, "we" keep doing that because "we" don't typically run on thousands of processors yet and don't notice that those turds left behind cause real problems.  Sorry about that.

**Comment by jrood-nrel** [comment]
@ldowen Do you mind if we make these changes in #181?

**Comment by ldowen** [comment]
@jrood Sure! I will go ahead and close this pull request then.

**Pull request closed without merging**
