### PR TITLE
skip computing reaction for covered fabs

### PR DESCRIPTION
**Pull request by rgrout**

### CODE REVIEW

**Comment by rgrout** [comment]
@drummerdoc somewhat tongue-in-cheek, but not inconsistent if 'covered' is interpreted as 'solution will be ignored because the physics aren't what it thinks they are'

**Comment by drummerdoc** [comment]
Right, but less informative for debugging/understanding purposes!

**Comment by rgrout** [comment]
Seems ready to go now. Thoughts?

**Comment by drummerdoc** [comment]
Since flag only exists in the fortran if USE_EB, does this code compile/work if not EB?

**Comment by rgrout** [comment]
I think I have ifdef guards around it - did I miss one? Seems to compile and run regression tests without eb ok

Sent from my iPhone

On Jun 27, 2019, at 5:26 PM, Marc Day <notifications@github.com<mailto:notifications@github.com>> wrote:


Since flag only exists in the fortran if USE_EB, does this code compile/work if not EB?

**Comment by drummerdoc** [comment]
How does Line 63 in React_nd.F90 build?

**Comment by rgrout** [comment]
Even more to the point, why did the CI tests pass?

Sent from my iPhone

On Jun 27, 2019, at 5:37 PM, Marc Day <notifications@github.com<mailto:notifications@github.com>> wrote:


How does Line 63 in React_nd.F90 build?

**Comment by drummerdoc** [comment]
Must be channeling Bell on this.

**Pull request merged**
