### PR TITLE
Update PelePhysics Submodule for October 2020

### PR DESCRIPTION
**Pull request by jrood-nrel**
Additions to #179 necessary to update PelePhysics to its latest `development` branch. Hopefully I didn't miss anything, but I tested this with SUNDIALS on the CPU and with SUNDIALS using CUDA on Summit as well.

### CODE REVIEW

**Review by ldowen — COMMENTED** [review]
Looks good to me. Seems consistent with my previous stuff.

**Review by hsitaram — APPROVED** [review]
I am ok with this if CI fail is not a problem now. We can fix that later.

**Review by marchdf — APPROVED** [review]

**Comment by jrood-nrel** [comment]
The failure has something to do with the symmetry test python script. Something seems to have changed recently on the Github images. I will have to look into it, but I think this would pass otherwise.

**Comment by asmunder** [comment]
With a fresh clone of PeleC and submodules, this commit ( 7e9abcf on development branch ) fails for me when doing just `make clean` in `Exec/RegTests/PMF_NSCBC`, with the error

`../../../Submodules/PelePhysics/Reactions/Fuego/Make.package:30: *** Activate USE_F90_PP to use dvode.  Stop`

Checking out the previous commit (b75d44) and doing `git submodule update --recursive`, everything seems to work fine.

**Comment by jrood-nrel** [comment]
Thanks @asmunder . I will work on this. I should have known all the PelePhysics updates would break F90.

**Comment by jrood-nrel** [comment]
I added `USE_F90_PP` in https://github.com/AMReX-Combustion/PeleC/commit/acf45f5e323ed436c2b01e74d0a09561222cfbc2

**Pull request merged**
