### PR TITLE
Hari/explicit react

### PR DESCRIPTION
**Pull request by hsitaram**
There was a bug in the timestep adaption in the explicit RK chemistry integration. I was not setting the error register to 0 before every time step; hence it was always running at the lowest possible timestep. I also updated sub-modules after which CMake is not working anymore - tried to remove the files that got deleted from amrex, but still having problems.

### CODE REVIEW

**Review by drummerdoc — COMMENTED** [review]
Good in concept...letting Steven weigh in on details.

**Review by ghost — APPROVED** [review]
Looks good to me.

**Comment by jrood-nrel** [comment]
I took a look at this. The problems with the CI were due to a CPP file that was just in an inconsistent state. I updated to the latest AMReX to fix it. The constant changes to AMReX source file names is exhausting though. I also fixed the HIT case errors I'm seeing on the tests with this update as well.

**Review by drummerdoc — APPROVED** [review]

**Review by jrood-nrel — APPROVED** [review]

**Comment by hsitaram** [comment]
Thank you Jon. I wasn't sure what was going on. I did add the new file names to amrex_sources.cmake but it was still failing. should we shift to amrex's cmake. It seems up-to-date. Also, can this be merged?

**Comment by jrood-nrel** [comment]
This can be merged. The filenames were right, but the syntax in one of the CPP files was in a bad state in the AMReX commit at the time of this PR so it was AMReX's fault. I still need to think about how we would be able to use AMReX's CMake directly.

**Pull request merged**
