### PR TITLE
Remove reset_internal_energy and fix volWgtSum to avoid multiplying m…

### PR DESCRIPTION
**Pull request by rgrout**
…f by vfrac. Latter should not impact correctness there, but avoids bugs if it is copied to remake something like volWgtSumMF that is currently removed

### CODE REVIEW

**Comment by rgrout** [comment]
Assigning @drummerdoc to merge this so that he can make sure CCSE stuff still builds with some routines stripped that I do not think are in use.

**Comment by drummerdoc** [comment]
@rgrout  can you look at the build failure.  That seems like something needing fixing first.

**Comment by rgrout** [comment]
Ok, fixed to allow for the non-EB world to build.

**Comment by rgrout** [comment]
I'm going to merge this in to make it easy to run MMS and then back it out if it breaks...

**Pull request merged**
