### PR TITLE
removing pelec_d_term_reverse

### PR DESCRIPTION
**Pull request by hsitaram**
using amrex_d_term instead for all stencils for better readability and memory access.

### CODE REVIEW

**Comment by marchdf** [comment]
This is great! I don't know why clang-tidy is complaining @jrood-nrel any ideas? It really feels like a false positive? 

I tried EB-C1 and C14 and get no diffs. 

I do see that C14 `nan`s for both this branch and `development` after running hundreds of steps. But I think that's another issue...

**Review by marchdf — APPROVED** [review]

**Comment by marchdf** [comment]
I am addressing the `nan` issue in PR #336

**Comment by jrood-nrel** [comment]
It wants a modern `for` loop on line 382 of `EB.cpp`. I neither agree nor disagree with it. You can just put `// NOLINT` at the end of that line.

**Comment by marchdf** [comment]
Yeah but why not on the next line too then? And what would that modern for loop look like?

**Comment by jrood-nrel** [comment]
`NOLINT` is on the line below.

**Comment by jrood-nrel** [comment]
I think it would be something like `for (int kk : grad_stencil[L].val)`, but I don't know how to do the multidimensional range based for loop in c++11.

**Comment by marchdf** [comment]
It's on the `kk` line, not the `jj` line.

**Comment by hsitaram** [comment]
ok nolinted it. lets see what happens

**Comment by marchdf** [comment]
Oh now I want to do:
```
for( auto &r0 : grad_stencil[L].val)
    for(auto &r1 : r0)
        for(auto &r2 : r1)
          r2 = 0.0; 
```

**Comment by jrood-nrel** [comment]
Hah, I think it could actually remove the need for `D_TERM` huh?

**Comment by marchdf** [comment]
huh good point... maybe it would!

**Review by jrood-nrel — APPROVED** [review]

**Pull request merged**
