### PR TITLE
2D EB capability

### PR DESCRIPTION
**Pull request by marchdf**

### CODE REVIEW

**Comment by marchdf** [comment]
C14 (with diffusion) pressure field: left is 2D and right is 3D simulation. Everything matches (including min/maxes)

Screen Shot 2021-06-01 at 3 32 10 PM

**Comment by marchdf** [comment]
Things I still want to do

- [x] add reg tests for 2D
- [x] ensure CI passes (hence the draft PR)
- [x] check EB regtests in 2D instead of 3D

**Comment by marchdf** [comment]
C7 Looks as expected: [profiles.pdf](https://github.com/AMReX-Combustion/PeleC/files/6587564/profiles.pdf)

**Comment by marchdf** [comment]
And also C8 (red vs green): 
profile

**Comment by marchdf** [comment]
C4 and C5 seem to be doing isothermal wall (temperature diffusion into domain) just fine: 

C5 early time:
C5 early time

C5 later time:
Screen Shot 2021-06-02 at 4 10 22 PM

**Comment by marchdf** [comment]
C13 looks fine: 
Screen Shot 2021-06-02 at 4 43 18 PM

**Comment by drummerdoc** [comment]
For the cases that are really 1D problems, how do the 2D results compare to the 3D results?

**Comment by marchdf** [comment]
@drummerdoc They are identical basically. For an acoustic pulse traveling down a channel (C12), it looks like this:

Screen Shot 2021-06-03 at 8 56 29 AM

2D: Top left density pseudocolor and red line in bottom left lineout
3D: Top right density pseudocolor and black dots in bottom left lineout

**Comment by marchdf** [comment]
This PR should be ready to go now.

**Review by jrood-nrel — APPROVED** [review]

**Pull request merged**
