### PR TITLE
Remove EB ifdef

### PR DESCRIPTION
**Pull request by jrood-nrel**
In the effort to remove compile time options, here we commit to having the EB code always enabled. The main drawback to doing so is that we give up 1D ability in PeleC which is barely hanging on and only works in very limited situations anyway. I think removing the ifdef and 1D is worth more than keeping 1D because it simplifies several areas.

### CODE REVIEW

**Comment by jrood-nrel** [comment]
Chart1
Here is a comparison running on the GPU. Two tests have a large slowdown we will probably need to investigate. I did three runs each and averaged them.

**Comment by jrood-nrel** [comment]
cpu
CPU looks similar.

**Comment by jrood-nrel** [comment]
After investigation, these tests just have higher initialization cost, and the timesteps in this branch look slightly faster.

**Comment by jrood-nrel** [comment]
This is ready and there are no diffs between the stdout reported quantities.

**Comment by jrood-nrel** [comment]
Screen Shot 2022-03-23 at 11 03 40 AM
I think we can solve the init cost for non-EB problems based on this profile.

**Comment by esclapez** [comment]
Yep, this is an expensive piece of code. We might need a more clever way to do that.

**Review by marchdf — APPROVED** [review]

**Review by baperry2 — APPROVED** [review]
This dramatically improves code readability so I am all for it.

The slight increase in per timestep performance is surprising though. Any idea why that's happening (or maybe it's just noise)?

**Comment by jrood-nrel** [comment]
I think it's noise. Without initialization increase (which I think @marchdf has since solved) in the graphs, runtimes look to be the same in general.

**Pull request merged**
