### PR TITLE
Add missing ebd.boundary_grad_stencil_type to EB input files

### PR DESCRIPTION
**Pull request by jrood-nrel**

### CODE REVIEW

**Comment by jrood-nrel** [comment]
All I know is doesn't exist means failure.

**Comment by hsitaram** [comment]
Moving forward, may be boundary_grad_stencil type should go into the _cpp_parameters framework. Hoping at some point we implement the other options _amrex and _ls?

**Comment by jrood-nrel** [comment]
I don't know why `fextrema` is broken on Travis here. Looks like it can't find pthread so I can try to fix this if it continues to happen. It doesn't matter for this PR since we don't test the Tutorials. The tutorials are broken until this is merged though.

**Comment by hsitaram** [comment]
I say we merge it

**Comment by drummerdoc** [comment]
I'm good.

**Comment by jrood-nrel** [comment]
Alright I'm going to merge this one because I want this in all the EB related cases for when I try to get EB on the GPU.

**Comment by rgrout** [comment]
Thanks!

Sent from my iPhone

On Aug 2, 2019, at 11:09 AM, Jon Rood <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #107<https://github.com/AMReX-Combustion/PeleC/pull/107> into development.

**Pull request merged**
