### PR TITLE
[feature_clean_CVODE]

### PR DESCRIPTION
**Pull request by EnnaDelfen**
Modif to react() to account for removed reInit param

### CODE REVIEW

**Comment by EnnaDelfen** [comment]
No idea what happened there... can someone enlighten me ? I see it failed in react, which is the thing I modified ?

**Comment by jrood-nrel** [comment]
@EnnaDelfen Travis CI here is relying on the submodules for AMReX and PelePhysics set in PeleC. It looks like https://github.com/AMReX-Combustion/PelePhysics/pull/36 needs to be merged first. Then I can make the necessary submodule updates to this pull request to get the tests passing.

**Comment by EnnaDelfen** [comment]
Hi Jon, I believe you can now update the submodules and let Travis try again !

**Comment by jrood-nrel** [comment]
✅

**Pull request merged**
