### PR TITLE
Update PMF reading to use PelePhysics

### PR DESCRIPTION
**Pull request by marchdf**

### CODE REVIEW

**Comment by jrood-nrel** [comment]
This doesn't run for me without managed memory on and it seems to be a few times slower.

**Comment by marchdf** [comment]
well bummer.

**Comment by esclapez** [comment]
I don't have a comparison of how slow in LM since it was already using this machinery, but I'll test the no managed mem. now.

**Comment by esclapez** [comment]
Provided a couple of fixes in IAMR/amrex to remove RunOn::Host, LM FlameSheet using PelePhysics PMF runs fine on Eagle with `amrex.the_arena_is_managed = 0` (but I get a `pure virtual method called` during the finalize that I need to investigate).

**Pull request closed without merging**
