### PR TITLE
Hari/explicit react

### PR DESCRIPTION
**Pull request by hsitaram**
1) Added explicit chemistry integrator in pelec along side VODE. It is not turned on right now due to a
hard-coded number of RK substeps. We will fix this using adaptive RK in a future PR.
2) added zeroD H2-O2 auto-ignition case
3) removed "molec_wt" from Src_nd/bc_fill - this variable does not exist
4) pc_react_state uses rhoe_new and rhoE_new which are the same in 
case-INSENSITIVE fortran but sensitive to us physicists - in do_update UINT and 
UEDEN were set to rhoE_new which is not correct. but UEINT is not directly used 
anywhere, so results didn't change.

### CODE REVIEW

**Comment by hsitaram** [comment]
I have tested this explicit integrator against the PMF case. The following is the fcompare results

           variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                            5.242217142e-12           5.097361558e-09
 xmom                               6.670215144e-09           2.900757301e-06
 ymom                               2.967539982e-08           1.215683961e-06
 zmom                                             0                         0
 rho_E                                0.01763226115           1.360201544e-08
 rho_e                                0.01763199107           1.360180105e-08
 Temp                               2.717646817e-05            1.90577727e-08
 rho_omega_H2                       3.962793486e-08           8.295321865e-06
 rho_omega_O2                       3.680494313e-07           9.789014713e-06
 rho_omega_H2O                      2.468886188e-07           6.213582832e-06
 rho_omega_H                        9.806760241e-09            3.60669485e-05
 rho_omega_O                        7.509255912e-08           3.996696284e-05
 rho_omega_OH                       1.335854267e-07           6.654887877e-05
 rho_omega_HO2                      8.814933924e-09           2.606586504e-05
 rho_omega_H2O2                     2.811646559e-09           4.615383909e-05

**Comment by hsitaram** [comment]
Also see picture of production-term for H2
pmf_compare

**Comment by hsitaram** [comment]
I have also added a 0D auto-ignition case for H2. See picture below for comparison with cantera. The explicit integrator needs more steps to be stable
pelec_0d

**Comment by drummerdoc** [comment]
So, Jackie's approach to the dubstep question is to have Tienfeng Lu generate a modified chemistry model that does not exhibit timescales shorter than the CFL dt. If that has been done, you should not see the issue you see.  If you haven't done this, and are using an "out of the box" model, how would one ever expect to be able to dial in the correct number of substeps?

**Comment by rgrout** [comment]
I believe that's next up - replacing the RK2 integrator with RK4 and embedded lower order method for error control.

**Comment by drummerdoc** [comment]
Oops, hit enter too early...

In other words, yes explicit chemistry is MUCH faster than VODE-integrated implicit chemistry, but how would you know how to dial in safe values for Nsub?

**Comment by drummerdoc** [comment]
Ahh...  How is this different than what is already available with DVODE/CVODE?

**Comment by rgrout** [comment]
@drummerdoc - No setup costs, no funny data structures, easy to vectorize over grid points.

@hariswaran - how does one control usage of this?

**Comment by hsitaram** [comment]
As of now comment out the line for pc_react_state_expl in pelec_react.cpp

**Comment by drummerdoc** [comment]
@rgrout You want to vectorize the error control?  Also, maybe we should meet up strategies with Anne's SDC work, which seems to be similar in spirit to this?  She is implementing in the context of PelePhysics so that it is available to PeleC and PeleLM.  It seems like we are growing variations in chemistry suddenly and will end up with a merge mess soon.  No?  Maybe a topic for discussion next week?

**Comment by rgrout** [comment]
@hsitaram Can you put a flag in the input file so that we can do pelec.chem_integrator = 1 for normal, 2 for explicit, 3 for when you do adaptive RK, etc?

**Comment by hsitaram** [comment]
sure. I can do that. Don't merge yet.

**Comment by rgrout** [comment]
@drummerdoc this is specific to PeleC I think, implementing the same strategy more or less that legacy explicit codes (e.g., S3D) use. Major motivation is to get away from setup costs that don't get amortized over a small dt.  I don't see how this would be useful for PeleLM...

Also, I don't see any harm (and actually see potential upside) to several different strategies. This one is driven by getting the near term milestone calculation done... but I would like to hear more about SDC chemistry work, if it's at all similar to this I don't think I understood what you are working on there.

**Comment by hsitaram** [comment]
I have added the pelec.chem_integrator option now

**Comment by jrood-nrel** [comment]
Adding the `rk_params.f90` source to the list of source files should solve the CI here:
```
$ git diff CMake/pelec_sources.cmake 
diff --git a/CMake/pelec_sources.cmake b/CMake/pelec_sources.cmake
index 87f18ac..1a67a15 100644
--- a/CMake/pelec_sources.cmake
+++ b/CMake/pelec_sources.cmake
@@ -118,6 +118,7 @@ function(get_pelec_sources pelec_exe_name)
      ${PELEC_SOURCE_DIR}/prob_params.f90
      ${PELEC_SOURCE_DIR}/problem_derive_nd.F90
      ${PELEC_SOURCE_DIR}/problem_tagging_nd.F90
+     ${PELEC_SOURCE_DIR}/rk_params.f90
      ${PELEC_SOURCE_DIR}/riemann_util.f90
      ${PELEC_SOURCE_DIR}/string_mod.f90
      ${PELEC_SOURCE_DIR}/sums_nd.f90
```

**Comment by rgrout** [comment]
Thanks @jrood-nrel !

**Comment by hsitaram** [comment]
Thanks guys.. I should have warned you of the new file.

**Pull request merged**
